version: '3.8'
services:

  backend:
    restart: unless-stopped
    container_name: backend
    image: "makezenerator/backend"
    ports:
      - 80:80
    env_file:
      .env.prod
    environment:
      FLASK_DEBUG: 1 #리로딩 설정
    command: gunicorn -w 1 -b 0.0.0.0:80 app:app --reload

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbit
    image: "rabbitmq:3-management"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "15672:15672"
      - "5672:5672"

  simple_worker:
    container_name: simple_worker
    image: "makezenerator/simple_worker"
    user: nobody
    env_file:
      .env.prod
    depends_on:
      - rabbitmq
      - backend
  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt 
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt 
      - ./data/certbot/www:/var/www/certbot