name: cicd

on:
  pull_request:
    branches:
      - 'main' # 메인이 푸쉬되었을 때 동작

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: build docker file and setting deploy files
        run: |
          cd backend
          docker build -t makezenerator/backend:lastest .
          docker push makezenerator/backend:lastest .
      - name : Connect to server 
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER_HOST}}
          username: root
          key: ${{secrets.SERVER_KEY}}
          script: |
            docker login -u "${{secrets.DOCKERHUB_USERNAME}}" -p "${{secrets.DOCKERHUB_TOKEN}}"
            docker pull makezenerator/backend:lastest
      
