name: cicd

on:
  pull_request:
    branches:
      - 'main' # 메인이 푸쉬되었을 때 동작

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run: python -c "print('hello world')"

      - name: Create .env file
        run: |
          echo "AWS_ACCESS_KEY = ${{secrets.AWS_ACCESS_KEY}}" > .env
          echo "AWS_SECRET_ACCESS_KEY = ${{secrets.AWS_SECRET_ACCESS_KEY}}" > .env
          echo "AWS_S3_BUCKET_REGION = ${{secrets.AWS_S3_BUCKET_REGION}}" > .env
          echo "AWS_S3_BUCKET_NAME = ${{secrets.AWS_S3_BUCKET_NAME}}" > .env
          echo "AWS_S3_BUCKET_URL = ${{secrets.AWS_S3_BUCKET_URL}}" > .env
          echo "USERNAME = ${{secrets.DB_USERNAME}}" > .env
          echo "PASSWORD = ${{secrets.DB_PASSWORD}}" > .env
          echo "HOST = ${{secrets.DB_HOST}}" > .env
          echo "DATABASE =${{secrets.DB_DATABASE}}" > .env
          echo "SECRET_KEY=${{secrets.SECRET_KEY}} > .env
          echo "TOKEN_EXPIRED=${{secrets.TOKEN_EXPIRED}} > .env
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: build docker file and setting deploy files
        run: |
          cd backend
          docker build -t makezenerator/backend:lastest .
          docker push makezenerator/backend:lastest .
      - name : Connect to server 
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER_HOST}}
          username: root
          key: ${{secrets.SERVER_KEY}}
          script: |
            docker login -u "${{secrets.DOCKERHUB_USERNAME}}" -p "${{secrets.DOCKERHUB_TOKEN}}"
            docker pull makezenerator/backend:lastest
      
