name: Backend

on:
  pull_request:
    branches: ['main'] # main 브랜치에 pull request될 때 동작 
  push:
    branches: ['main'] # main 브랜치에 push될 때 동작

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      - name: Build docker file and setting deploy files
        run: |
          docker build -t makezenerator/backend:latest backend/
          docker push makezenerator/backend:latest
          docker build -t makezenerator/simple_worker:latest backend/simple_worker/
          docker push makezenerator/simple_worker:latest
  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: Connect to server 
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER_HOST}}
          username: ${{secrets.SERVER_USERNAME}}
          key: ${{secrets.SERVER_KEY}}
          port: ${{secrets.SERVER_PORT}}
          script: | 
            docker login -u "${{secrets.DOCKERHUB_USERNAME}}" -p "${{secrets.DOCKERHUB_PASSWORD}}"
            docker stop $(docker ps -a -q)
            docker rm -f $(docker ps -a -q)
            docker pull makezenerator/backend:latest
            docker pull makezenerator/simple_worker:latest
            # docker run -d -p 5050:5050 makezenerator/backend:latest
            cd voice2face-backend
            git pull origin main
            docker compose -f /root/voice2face-backend/backend/docker-compose.prod.yml up -d 
            docker image prune -f
